apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-lookup-service-{{ .Values.env }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: helm/car-lookup-service
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.env }}.yaml
      parameters:
        - name: image.tag
          value: {{ .Values.appVersion | quote }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ index .Values.namespace .Values.env }}

  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
